[tool.coverage.run]
branch = true
source = ["src/django_multisite_plus", "./tests"]
data_file = ".artifacts/coverage"

[tool.coverage.paths]
source = [
    "src",
    "~/.toxenvs/django-multisite-plus/*/lib*/python*/site-packages",
]

[tool.coverage.report]
precision = 1
#skip_covered = true

[tool.coverage.html]
directory = ".artifacts/htmlcov"
show_contexts = true
skip_covered = false

[tool.pytest.ini_options]
pythonpath = "./tests"
addopts = "-rxs --import-mode=importlib --cov-report= --cov=django_multisite_plus --cov=tests"
