[tool.coverage.run]
branch = true
source = ["django_multisite_plus"]
data_file = ".artifacts/coverage"

[tool.coverage.paths]
source = [
    "src/django_multisite_plus",
    "~/.toxenvs/django-multisite-plus/*/lib*/python*/site-packages/django_multisite_plus",
]


[tool.coverage.report]
precision = 1
#skip_covered = true

[tool.coverage.html]
directory = ".artifacts/htmlcov"
show_contexts = true
skip_covered = false
